services:
  enrichard-app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: enrichard_container

    ports:
      - "8501:8501"

    volumes:
      - ./app:/app
    
    command: ["/start.sh"]
