services:
  enrichard-app:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: enrichard_container
    
    environment:
    - COMMON_BACKGROUND=/app/Common_Background
    - USER_CUSTOM_BACKGROUND_NAME=user_background.txt
    - USER_SAMPLE_NAME=user_sample.txt
    - USER_MODULE_OUTPUT=Module_output
    - RUN_MODE=server #local
    user: "1006:1006"
    ports:
      - "8501:8501"

    volumes:
      - ./app:/app
    
    command: ["bash", "/app/start.sh"]
